-- V009: Add task-oriented fields to session table

DROP PROCEDURE IF EXISTS add_session_task_fields;
DELIMITER //
CREATE PROCEDURE add_session_task_fields()
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND COLUMN_NAME = 'phase') THEN
        ALTER TABLE `session` ADD COLUMN `phase` VARCHAR(32) DEFAULT 'IDLE' COMMENT 'IDLE|RUNNING|WAITING_USER|WAITING_APPROVAL|COMPLETED|FAILED';
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND COLUMN_NAME = 'summary') THEN
        ALTER TABLE `session` ADD COLUMN `summary` VARCHAR(512) NULL COMMENT '任务一句话摘要';
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND COLUMN_NAME = 'started_at') THEN
        ALTER TABLE `session` ADD COLUMN `started_at` DATETIME NULL COMMENT '本轮执行开始时间';
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND COLUMN_NAME = 'elapsed_ms') THEN
        ALTER TABLE `session` ADD COLUMN `elapsed_ms` BIGINT DEFAULT 0 COMMENT '累计执行毫秒';
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND COLUMN_NAME = 'steps_json') THEN
        ALTER TABLE `session` ADD COLUMN `steps_json` JSON NULL COMMENT '进度步骤 [{id,label,done}]';
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND COLUMN_NAME = 'project_key') THEN
        ALTER TABLE `session` ADD COLUMN `project_key` VARCHAR(256) NULL COMMENT 'workspace 基名或用户定义项目名';
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND COLUMN_NAME = 'last_activity_at') THEN
        ALTER TABLE `session` ADD COLUMN `last_activity_at` DATETIME NULL;
    END IF;

    -- Add index if not exists
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session' AND INDEX_NAME = 'idx_session_user_phase') THEN
        CREATE INDEX `idx_session_user_phase` ON `session` (`user_id`, `phase`);
    END IF;
END //
DELIMITER ;
CALL add_session_task_fields();
DROP PROCEDURE add_session_task_fields;
