UPDATE `session`
SET `phase` = 'IDLE'
WHERE `phase` = 'WAITING_USER';

ALTER TABLE `session`
    MODIFY COLUMN `phase` VARCHAR(32) DEFAULT 'IDLE'
    COMMENT 'IDLE|RUNNING|RESUMING|WAITING_APPROVAL|COMPLETED|FAILED|CANCELLED';
