-- 用户级微信通道偏好：语音回复开关
CREATE TABLE IF NOT EXISTS user_weixin_preference (
    user_id BIGINT PRIMARY KEY COMMENT '用户ID',
    voice_reply TINYINT NOT NULL DEFAULT 0 COMMENT 'Agent 回复是否附带语音：0=关闭 1=开启',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户微信通道偏好';
