-- 逐次 LLM 调用流水（对话、压缩、标题、后台任务等每次 chat/stream 一行）
CREATE TABLE IF NOT EXISTS `llm_call` (
  `id`                  BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id`             BIGINT NULL COMMENT '触发用户 ID（群聊为 executionUserId）',
  `session_id`          BIGINT NULL COMMENT '关联会话 ID',
  `agent_id`            BIGINT NULL COMMENT '关联 Agent ID',
  `model_id`            BIGINT NULL COMMENT '平台模型 ID（llm_model.id）',
  `model_name`          VARCHAR(128) NULL COMMENT '模型展示名（冗余快照）',
  `provider`            VARCHAR(64) NULL COMMENT '供应商（冗余快照）',
  `provider_model_id`   VARCHAR(128) NULL COMMENT '上游 modelId（冗余快照）',
  `scene`               VARCHAR(64) NOT NULL DEFAULT 'unknown' COMMENT '调用场景：agent/compaction/session_title/git_commit_message/danger_assess/voice_synthesis/feishu_summarize/connectivity_test/unknown',
  `stream`              TINYINT NOT NULL DEFAULT 0 COMMENT '是否流式调用：0=否，1=是',
  `effort`              VARCHAR(32) NULL COMMENT '推理强度 effort',
  `protocol`            VARCHAR(64) NULL COMMENT 'API 协议：openai-compatible/anthropic/openai-responses 等',
  `prompt_tokens`       INT NOT NULL DEFAULT 0 COMMENT '输入 token 数',
  `completion_tokens`   INT NOT NULL DEFAULT 0 COMMENT '输出 token 数',
  `cached_tokens`       INT NOT NULL DEFAULT 0 COMMENT '缓存命中 token 数',
  `total_tokens`        INT NOT NULL DEFAULT 0 COMMENT '合计 token 数',
  `success`             TINYINT NOT NULL DEFAULT 0 COMMENT '是否成功：0=失败，1=成功',
  `error_message`       VARCHAR(512) NULL COMMENT '失败原因摘要（截断）',
  `first_token_ms`      INT NULL COMMENT '首 token 延迟毫秒（流式）',
  `duration_ms`         INT NOT NULL DEFAULT 0 COMMENT '总耗时毫秒（含适配器重试）',
  `retry_count`         INT NOT NULL DEFAULT 0 COMMENT '适配器内部重试次数',
  `created_at`          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '调用时间',
  INDEX `idx_llm_call_created` (`created_at`),
  INDEX `idx_llm_call_user_created` (`user_id`, `created_at`),
  INDEX `idx_llm_call_session_created` (`session_id`, `created_at`),
  INDEX `idx_llm_call_model_created` (`model_id`, `created_at`),
  INDEX `idx_llm_call_scene_created` (`scene`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='LLM 调用流水';
