export const ErrorCode = {
  UNAUTHORIZED: { code: 1001, message: '未登录或登录已过期' },
  FORBIDDEN: { code: 1002, message: '无权限访问' },
  TOKEN_EXPIRED: { code: 1003, message: 'Token 已过期' },
  TOKEN_INVALID: { code: 1004, message: 'Token 无效' },
  LOGIN_FAILED: { code: 1005, message: '用户名或密码错误' },
  ACCOUNT_DISABLED: { code: 1006, message: '账号已被禁用' },

  PARAM_INVALID: { code: 2001, message: '参数校验失败' },
  PARAM_MISSING: { code: 2002, message: '缺少必要参数' },

  AGENT_NOT_FOUND: { code: 3001, message: 'Agent 不存在' },
  SESSION_NOT_FOUND: { code: 3002, message: '会话不存在' },
  MODEL_NOT_FOUND: { code: 3003, message: '模型配置不存在' },
  SKILL_NOT_FOUND: { code: 3004, message: 'Skill 不存在' },
  AGENT_ACCESS_DENIED: { code: 3005, message: '无权访问该 Agent' },
  MODEL_IS_DEFAULT: { code: 3006, message: '不能删除默认模型，请先修改默认模型' },
  LLM_CALL_FAILED: { code: 3007, message: 'LLM 调用失败' },
  LLM_TIMEOUT: { code: 3008, message: 'LLM 调用超时' },
  AGENT_IS_DEFAULT: { code: 3009, message: '不能删除默认 Agent，请先修改默认 Agent' },
  SKILL_NAME_DUPLICATE: { code: 3010, message: 'Skill 名称已存在' },
  COMMAND_NOT_FOUND: { code: 3011, message: '指令不存在' },
  COMMAND_NAME_DUPLICATE: { code: 3012, message: '指令名称已存在' },
  COMMAND_NAME_INVALID: { code: 3013, message: '指令名称只能包含字母、数字、中文、下划线和连字符' },
  USER_NOT_FOUND: { code: 3014, message: '用户不存在' },
  USERNAME_DUPLICATE: { code: 3015, message: '用户名已存在' },
  CANNOT_DISABLE_SELF: { code: 3016, message: '不能禁用当前登录用户' },
  CANNOT_REMOVE_LAST_ADMIN: { code: 3017, message: '不能移除最后一个管理员' },
  USER_PASSWORD_MANAGED_BY_LDAP: { code: 3018, message: 'LDAP 用户密码由目录服务管理' },
  PASSWORD_INVALID: { code: 3019, message: '密码格式不符合要求' },
  COMMAND_SYSTEM_READONLY: { code: 3020, message: '系统预置指令不可编辑或删除' },
  GIT_CREDENTIAL_NOT_FOUND: { code: 3021, message: 'Git 凭证不存在' },
  GIT_CREDENTIAL_DOMAIN_DUPLICATE: { code: 3022, message: '该域名的凭证已存在' },
  AGENT_EXPERIENCE_CONTENT_INVALID: { code: 3023, message: '最佳实践经验内容无效（需 1～300 字）' },
  AGENT_EXPERIENCE_NOT_FOUND: { code: 3024, message: '最佳实践经验不存在' },
  SCHEDULED_TASK_NOT_FOUND: { code: 3025, message: '定时任务不存在' },
  SCHEDULED_TASK_ACCESS_DENIED: { code: 3026, message: '无权操作该定时任务' },
  MESSAGE_ALREADY_COMPACTED: { code: 3027, message: '该消息已进入会话摘要，无法编辑' },

  INTERNAL_ERROR: { code: 5001, message: '服务内部错误' },
  DATABASE_ERROR: { code: 5002, message: '数据库错误' },
  FILE_UPLOAD_ERROR: { code: 5004, message: '文件上传失败' },
  GIT_CLONE_FAILED: { code: 5005, message: 'Git 仓库克隆失败' },
} as const;

export type ErrorCodeDef = { readonly code: number; readonly message: string };
